#!/bin/bash

nixdots-cmd-present "$EDITOR" || EDITOR=nvim

case "${EDITOR:-nvim}" in
nvim | vim | nano | micro | hx | helix)
  exec setsid uwsm-app -- xdg-terminal-exec "$EDITOR" "$@"
  ;;
*)
  exec setsid uwsm app -- "$EDITOR" "$@"
  ;;
esac
